"""敵・行商人・宝箱・薬草のテンプレート（16×16）。

B=体、L=明るい面、D=影や脚、A=目や模様、"."=透過。小文字・数字はそのままの色。
同じ形を色違いで使い回すときは、出る階が重ならない組み合わせにする。
"""

TEMPLATES: dict[str, list[str]] = {
    "blob": [
        "................",
        "................",
        "................",
        ".......LL.......",
        "......LBBB......",
        ".....LBBBBB.....",
        "....LLBBBBBB....",
        "...LBBBBBBBBB...",
        "..LBBBBBBBBBBB..",
        "..BBA7BBBBA7BB..",
        ".BBBAABBBBAABBB.",
        ".BBBBBBBBBBBBBB.",
        ".BBBBBBBBBBBBBD.",
        "BBBBBBBBBBBBBBBD",
        ".DDDDDDDDDDDDDD.",
        "................",
    ],
    # ネズミ（左向き。丸い耳と長い尻尾）
    "rat": [
        "................",
        "................",
        "................",
        "................",
        "................",
        ".BB.BB..........",
        ".BLBBL..........",
        "BBA7BBBLLL......",
        "BBBBBBBBBBBLL...",
        "DBBBBBBBBBBBBL..",
        ".BBBBBBBBBBBBBB.",
        "..BBBBBBBBBBBBBD",
        "..DBBBBBBBBBBD.D",
        "..DD.DD..DD.DD.D",
        "..............D.",
        "................",
    ],
    # トカゲ（左向き。低い胴と背中のとげ）
    "lizard": [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        ".BBBB...........",
        "BA7BLL..........",
        "BBBBBBBL..L.L...",
        "DBBBBBBBBBBBB...",
        ".DBBLLLBBBBBBBB.",
        "..BBBBBBBBBBBDBB",
        "..D.D....D.D..DB",
        ".DD.DD..DD.DD..D",
        "................",
        "................",
    ],
    # 犬（左向き。立った耳と長い脚）
    "hound": [
        "................",
        "................",
        "...B.B..........",
        "...BBB..........",
        "..BA7B..........",
        "B7BBBB.........D",
        "DBBBBBL.......D.",
        "...BBBBLLLLLLBD.",
        "...BBBBBBBBBBBD.",
        "...BBBBBBBBBBB..",
        "...BBD.....DBB..",
        "...BD......DB...",
        "...BD......DB...",
        "..BB......BB....",
        "................",
        "................",
    ],
    "flyer": [
        "................",
        "................",
        "................",
        "B..............B",
        "BB....B..B....BB",
        "BBB...BBBB...BBB",
        "BLBB..BBBB..BBLB",
        "BLLBBBBBBBBBBLLB",
        "BBLBBA7BBA7BBLBB",
        ".BBBBBBBBBBBBBB.",
        "..BB.DBBBBD.BB..",
        "...B..DBBD..B...",
        ".......DD.......",
        "......D..D......",
        "................",
        "................",
    ],
    # キノコ（笠は B と L、柄は D。目は紺）
    "mushroom": [
        "................",
        ".....BBBBBB.....",
        "...BBLLBBBBBB...",
        "..BLLBB77BBBBB..",
        ".BBLBBBBBBB77BB.",
        ".B77BBBBBBBBBBB.",
        "BBBBBBB77BBBBBBB",
        "..DDDDDDDDDDDD..",
        "....DDDDDDDD....",
        "....D1DDDD1D....",
        "....D1DDDD1D....",
        "...DDDDDDDDDD...",
        "..D.DDDDDDDD.D..",
        "....DDDDDDDD....",
        "....DD....DD....",
        "...DDD....DDD...",
    ],
    "humanoid": [
        "......BBBB......",
        ".....BLBBBB.....",
        ".....AABBAA.....",
        ".....BBBBBB.....",
        "......BDDB......",
        ".......BB.......",
        "....BBBBBBBB....",
        "....BLBBBBDB....",
        "...B.LBBBDB.B...",
        "...B.BBBBDB.B...",
        "..BB.BBBBDB.BB..",
        ".....DDDDDD.....",
        ".....BB..BB.....",
        ".....BB..BB.....",
        ".....BB..BB.....",
        "....DDD..DDD....",
    ],
    # 騎士（兜・盾(A)・剣）
    "knight": [
        "......BBBB......",
        ".....BLLBB......",
        ".....BDDDDB.....",
        ".....DADDAD.....",
        ".....BBBBBB.....",
        "......BDDB......",
        "..AA.BBBBBB..7..",
        ".AAAABLBBBBB.7..",
        ".ALLABLBBBDB.7..",
        ".ALLABBBBBDBB7..",
        ".AAAABBBBBDB.d..",
        "..AA.DDDDDD.....",
        ".....BB..BB.....",
        ".....BB..BB.....",
        ".....BB..BB.....",
        "....DDD..DDD....",
    ],
    # 行商人（頭巾と大きな背負い袋。顔は肌色）
    "merchant": [
        "................",
        "......BBBB......",
        ".....BLLBBB.....",
        "....BLBBBBBB....",
        "....BBffffBB....",
        "....Bf1ff1fB....",
        "....BBffffBB....",
        "...DDBBBBBBDD...",
        "..DDDBLBBBBBDDD.",
        "..DDDBLBBAABDDD.",
        "..DDDBBBBAABDDD.",
        "..DDDBBBBBBBDDD.",
        "...DDBBBBBBBDD..",
        ".....BBBBBBB....",
        ".....DD...DD....",
        "....DDD...DDD...",
    ],
    "serpent": [
        "................",
        "..........BBB...",
        ".........BBA7B..",
        ".........BBBBBD.",
        "..........BBL...",
        "...........BL...",
        "....BBBBB..BL...",
        "...BLLLLBB.BL...",
        "..BL.....BBBL...",
        "..BL..BBBB......",
        "..BL.BLDDBB.....",
        "..BBLD...BBB....",
        "...BBBDDDBBBL...",
        "....BBBBBBBBBBB.",
        ".....DDDDDDDDD..",
        "................",
    ],
    "centipede": [
        "................",
        "................",
        "................",
        "................",
        "B...............",
        ".B..............",
        "BBBB.BBB.BBB.BB.",
        "BA7BLBBLLBBLLBBL",
        "BBBBBBBBBBBBBBBB",
        "DBBBDBBBDBBBDBBD",
        ".DDD.DDD.DDD.DD.",
        "..D...D...D...D.",
        ".D...D...D...D..",
        "................",
        "................",
        "................",
    ],
    # クモ（8本脚。目は胴の前にまとめる）
    "spider": [
        "................",
        "................",
        "................",
        "..D..........D..",
        "...D..BBBB..D...",
        "D...DBLLBBBD...D",
        ".D..DBLBBBBD..D.",
        "..DDBBBBBBBBDD..",
        "....BBAABAABB...",
        "..DDBBBBBBBBDD..",
        ".D..DBBBBBBD..D.",
        "D..D..BDDB..D..D",
        "...D...77...D...",
        "..D..........D..",
        "................",
        "................",
    ],
    # 甲虫（真上から見た硬い殻。中央に殻の合わせ目）
    "beetle": [
        "................",
        "................",
        ".......DD.......",
        "......DBBD......",
        ".....DDAADD.....",
        "..D.DBBBBBBD.D..",
        "...DBLLDDBBBD...",
        "D.DBLLBDDBBBBD.D",
        ".DDBLBBDDBBBBDD.",
        "..DBLBBDDBBBBD..",
        "D.DBBBBDDBBBBD.D",
        ".D.DBBBDDBBBD.D.",
        "....DBBDDBBD....",
        "...D.DDDDDD.D...",
        "..D..........D..",
        "................",
    ],
    "ghost": [
        "................",
        "......BBBB......",
        "....BBLLBBBB....",
        "...BLLBBBBBBB...",
        "...BLBBBBBBBB...",
        "..BBBAABBBAABB..",
        "..BBBAABBBAABB..",
        "..BBBBBBBBBBBB..",
        "..BBBBBDDBBBBB..",
        "..BBBBBDDBBBBB..",
        ".BBBBBBBBBBBBBB.",
        "BB.BBBBBBBBBB.BB",
        "...BBBBBBBBBB...",
        "...BBBBBBBBBBB..",
        "...B.BBB.BBB.B..",
        "......B...B.....",
    ],
    # 鬼火（揺らめく炎。L が外側の炎、芯は白）
    "wisp": [
        "................",
        ".......L........",
        "......LL........",
        "......LBL.......",
        ".....LBBL..L....",
        ".....LBBBL.LL...",
        "....LBBBBBLBL...",
        "...LBBB77BBBBL..",
        "...LBB7777BBBL..",
        "..LBBBA77ABBBBL.",
        "..LBBBBAABBBBBL.",
        "..LBBBBBBBBBBBL.",
        "...LBBBBBBBBBL..",
        "....LDBBBBBDL...",
        ".....LDDDDDL....",
        "................",
    ],
    "golem": [
        "....BBBBBBBB....",
        "...BLLBBBBBBD...",
        "...BLAABBAABD...",
        "...BBBBBBBBBD...",
        "....BBDDDDBB....",
        ".BBBBBBBBBBBBBB.",
        "BLLBBBBBBBBBBBDB",
        "BLBBBBDBBDBBBBDB",
        "BLBBBBBDDBBBBBDB",
        "BBB.BBBBBBBB.BDD",
        "DDD.BBBBBBBB.DDD",
        "....BBBDDBBB....",
        "....BBB..BBB....",
        "....BBB..BBB....",
        "...BBBB..BBBB...",
        "...DDDD..DDDD...",
    ],
    # ミミック（口を開けた宝箱。歯は白、舌は赤）
    "mimic": [
        "................",
        "..BBBBBBBBBBBB..",
        ".BLLLLLLLLLLLLB.",
        ".BBBBBBBBBBBBBB.",
        ".BD7D7D7D7D7D7B.",
        ".BDADDDDDDDDADB.",
        ".BDDDDD88DDDDDB.",
        ".B7D7D7D7D7D7DB.",
        ".BBBBBBAABBBBBB.",
        ".BLLLLLAALLLLLB.",
        ".BBBBBBBBBBBBBB.",
        ".BDDBBBBBBBBDDB.",
        ".BBBBBBBBBBBBBB.",
        ".DDDDDDDDDDDDDD.",
        "..D..........D..",
        ".DD..........DD.",
    ],
    "chest_closed": [
        "................",
        "................",
        "................",
        "..DDDDDDDDDDDD..",
        ".DBLLLLLLLLLLBD.",
        ".DBBBBBBBBBBBBD.",
        ".DAABBBBBBBBAAD.",
        ".DDDDDDAADDDDDD.",
        ".DAABBBAABBBAAD.",
        ".DBBBBBDDBBBBBD.",
        ".DBBBBBBBBBBBBD.",
        ".DAABBBBBBBBAAD.",
        ".DDDDDDDDDDDDDD.",
        "................",
        "................",
        "................",
    ],
    "chest_open": [
        "................",
        "..DDDDDDDDDDDD..",
        ".DBBBBBBBBBBBBD.",
        ".DAABBBBBBBBAAD.",
        ".DDDDDDDDDDDDDD.",
        ".DDDDDDDDDDDDDD.",
        ".DLLLLLLLLLLLLD.",
        ".DBBBBBBBBBBBBD.",
        ".DAABBBBBBBBAAD.",
        ".DBBBBBBBBBBBBD.",
        ".DBBBBBBBBBBBBD.",
        ".DAABBBBBBBBAAD.",
        ".DDDDDDDDDDDDDD.",
        "................",
        "................",
        "................",
    ],
    # 薬草（2枚の葉と茎。A=茎）
    "leaf": [
        "................",
        "...........DDD..",
        ".........DBBBBD.",
        "........DBBLLBD.",
        ".......DBBLBBD..",
        "..DDD..DBLBBD...",
        ".DBBBD.DLBBD....",
        "DBBLLBDDLBD.....",
        "DBLBBBBADD......",
        ".DBBBBA.........",
        "..DDDA..........",
        ".....A..........",
        "....A...........",
        "...A............",
        "................",
        "................",
    ],
}

# 敵ID → (テンプレート, 体, 目や模様, 影, 明るい面)。
# 体の色は、出現する階の床の色と同じにしない（背景に溶けて見えなくなるため）。
MONSTERS: dict[str, tuple[str, int, int, int, int]] = {
    "slime": ("blob", 11, 1, 3, 7),
    "giant_rat": ("rat", 13, 8, 5, 6),
    "cave_bat": ("flyer", 2, 8, 1, 14),
    "mushroom_man": ("mushroom", 8, 7, 15, 14),
    "skeleton": ("humanoid", 7, 1, 13, 6),
    "serpent": ("serpent", 3, 10, 1, 11),
    "fire_lizard": ("lizard", 9, 10, 8, 10),
    "mimic": ("mimic", 4, 10, 1, 9),
    "armored_centipede": ("centipede", 5, 8, 13, 6),
    "rock_golem": ("golem", 13, 10, 5, 6),
    "shadow_wraith": ("ghost", 2, 8, 1, 14),
    "labyrinth_hound": ("hound", 4, 8, 2, 9),
    "cave_spider": ("spider", 1, 8, 5, 13),
    "bog_slime": ("blob", 12, 1, 5, 6),
    "ghoul": ("humanoid", 6, 8, 5, 7),
    "wisp": ("wisp", 10, 8, 9, 7),
    "stone_beetle": ("beetle", 13, 8, 5, 6),
    "bone_knight": ("knight", 7, 12, 5, 6),
    "lava_newt": ("lizard", 8, 10, 2, 14),
    "void_moth": ("flyer", 14, 7, 2, 15),
}

# 迷宮の行商人（仕様書 12.4）。敵と見間違えないよう、明るい緑の人型にする。
# キー名はゲーム本体の game/world/tiles.py の MERCHANT_SPRITE と合わせること
# （ツールは本体から import しない決まりのため、ここでは同じ文字列を書く）。
MERCHANT_SPRITE = "merchant"
MERCHANT: tuple[str, int, int, int, int] = ("merchant", 11, 10, 3, 7)

# 宝箱（体, 金具, 影, 明るい面）
CHEST_COLORS: tuple[int, int, int, int] = (4, 10, 1, 9)

# 薬草のアイテムID → (葉, 茎, 影, 明るい面)
LEAVES: dict[str, tuple[int, int, int, int]] = {
    "item_herb": (11, 4, 3, 7),
    "item_mana_herb": (12, 4, 5, 6),
    "item_antidote": (14, 4, 2, 15),
}
